name: "CI"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1.0.1
        with:
          bats-version: 1.1.0

      - name: Check out code
        uses: actions/checkout@v1

      - name: initialise submodules
        run: git submodule update --init

      - name: Test
        run: make test
