name: ShellCheck
on: [push, pull_request]
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        check_together: 'yes'
        ignore_paths: 'cellar lib tests completions man bin docs'
        version: v0.8.0
